name: On Pull Request

on:
    pull_request:
        types: [opened, synchronize]

permissions:
    contents: write
    pull-requests: read

jobs:
    terraform-checks:
        uses: ./.github/workflows/terraform-checks.yaml
        with:
            ref: ${{ github.event.pull_request.head.sha }}
            push_branch: ${{ github.event.pull_request.head.ref }}
        secrets: inherit