name: Terraform Checks

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      push_branch:
        required: false
        type: string
        default: ''

permissions:
  contents: write

jobs:
  tflint:
    name: Run TFLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 1

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: v0.61.0

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint --disable-rule=terraform_required_version

  terraform-fmt:
    name: Terraform Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3

      - name: Terraform Format
        run: terraform fmt --recursive .

      - name: Commit changes
        if: inputs.push_branch != ''
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "No formatting changes detected."
            exit 0
          fi

          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -u
          git commit -m "Auto-format Terraform files"
          git push origin HEAD:${{ inputs.push_branch }}
